hyperskill_project:
  id: 215
  ide_files: https://cogniterra.org/media/attachments/lesson/26063/additional_files.json
  is_template_based: false
  use_ide: true
  environment: unittest
update_date: "Sat, 20 Apr 2024 12:45:11 UTC"
stages:
  - id: 1077
    step: 16548
    is_completed: false
  - id: 1078
    step: 16549
    is_completed: false
  - id: 1079
    step: 16550
    is_completed: false
  - id: 1080
    step: 16551
    is_completed: false
topics:
  0:
    - title: Introduction to UI/UX
      theory_id: 14603
    - title: Layout grids
      theory_id: 14922
    - title: Interface elements
      theory_id: 15253
    - title: World Wide Web
      theory_id: 6633
    - title: "HTTP: HyperText Transfer Protocol"
      theory_id: 6569
    - title: Operating systems
      theory_id: 9704
    - title: Command line overview
      theory_id: 8977
    - title: Parameters and options
      theory_id: 9746
    - title: Units of information
      theory_id: 6865
    - title: HTTP URL
      theory_id: 6740
    - title: Block-level elements
      theory_id: 7271
    - title: Inline elements
      theory_id: 7518
    - title: HTTP messages
      theory_id: 6752
    - title: REST
      theory_id: 7834
    - title: What is CSS
      theory_id: 7678
    - title: HTML attributes id and class
      theory_id: 7527
    - title: Domains
      theory_id: 6911
    - title: Intro to HTML forms
      theory_id: 6560
    - title: IP
      theory_id: 13662
    - title: What is an HTTP server?
      theory_id: 25834
    - title: Introduction to Flask
      theory_id: 17324
    - title: Routes
      theory_id: 17350
    - title: Requests
      theory_id: 17333
    - title: Responses
      theory_id: 17392
    - title: Web development
      theory_id: 13931
    - title: Introduction to Python
      theory_id: 5204
    - title: Writing first program
      theory_id: 5208
    - title: "PEP 8: Coding style guide"
      theory_id: 5879
    - title: Multi-line programs
      theory_id: 5233
    - title: Naming variables
      theory_id: 5885
    - title: Taking user's input
      theory_id: 5913
    - title: Program with numbers
      theory_id: 5872
    - title: If statement
      theory_id: 5953
    - title: Else statement
      theory_id: 5932
    - title: Comments
      theory_id: 6081
    - title: Importing modules
      theory_id: 6019
    - title: Creating modules
      theory_id: 6057
    - title: Multiple modules. Package
      theory_id: 6384
    - title: Installing packages with pip
      theory_id: 6230
    - title: Virtual Environment
      theory_id: 13923
    - title: Libraries
      theory_id: 8504
    - title: Frameworks
      theory_id: 6701
    - title: Elif statement
      theory_id: 5926
    - title: While loop
      theory_id: 5940
    - title: Class
      theory_id: 6661
    - title: Class instances
      theory_id: 6669
    - title: Methods
      theory_id: 6931
    - title: Methods and attributes
      theory_id: 6981
    - title: Magic methods
      theory_id: 7139
    - title: Inheritance
      theory_id: 9844
    - title: Inheritance in Python
      theory_id: 7235
    - title: Polymorphism
      theory_id: 10027
    - title: Method overriding
      theory_id: 7629
    - title: HTML basics
      theory_id: 6434
    - title: Introduction to software architecture
      theory_id: 15368
    - title: Tags and Attributes
      theory_id: 7536
    - title: HTML page structure
      theory_id: 6491
    - title: Program execution
      theory_id: 6047
    - title: Errors
      theory_id: 6052
    - title: Exceptions
      theory_id: 6042
    - title: Built-in exceptions
      theory_id: 11680
    - title: Exception handling
      theory_id: 6270
    - title: User-defined exceptions
      theory_id: 10217
    - title: JSON
      theory_id: 6854
    - title: Basic data types
      theory_id: 5852
    - title: Variables
      theory_id: 5859
    - title: Integer arithmetic
      theory_id: 5865
    - title: Invoking functions
      theory_id: 5891
    - title: Boolean type and operations. True and false
      theory_id: 6025
    - title: Comparisons
      theory_id: 5920
    - title: Declaring functions
      theory_id: 5900
    - title: Global vs local. Scopes
      theory_id: 6322
    - title: Quotes and multi-line strings
      theory_id: 5814
    - title: String formatting
      theory_id: 6037
    - title: Function decorators
      theory_id: 10103
    - title: MVC
      theory_id: 17197
  1:
    - title: Access from browser
      theory_id: 17374
    - title: Intro to templates and rendering
      theory_id: 17702
    - title: Error handlers
      theory_id: 17366
    - title: Help files
      theory_id: 13309
    - title: Getting data from net
      theory_id: 13915
    - title: Access from console
      theory_id: 17383
    - title: Intro to RESTful  Flask
      theory_id: 18174
    - title: Command line arguments
      theory_id: 7981
    - title: Introduction to Linux
      theory_id: 9526
    - title: Introduction to API
      theory_id: 17007
    - title: List
      theory_id: 5979
    - title: Indexes
      theory_id: 6189
    - title: Type casting
      theory_id: 6224
  2:
    - title: What is object-oriented programming
      theory_id: 3614
    - title: What are databases
      theory_id: 8497
    - title: "SQL: structured query language"
      theory_id: 7054
    - title: Basic data types
      theory_id: 7123
    - title: Literals
      theory_id: 7400
    - title: Arithmetic expressions
      theory_id: 7409
    - title: Basic CREATE statement
      theory_id: 9084
    - title: Basic SELECT statement
      theory_id: 7392
    - title: SELECT FROM statement
      theory_id: 8611
    - title: Logic and comparison expressions
      theory_id: 8619
    - title: Basic INSERT statement
      theory_id: 9059
    - title: Basic DELETE statement
      theory_id: 9075
    - title: Introduction to SQLite
      theory_id: 12165
    - title: Introduction to logging
      theory_id: 5538
    - title: XML
      theory_id: 6901
    - title: Data and object mapping
      theory_id: 8262
    - title: Object-Relational Mapping (ORM)
      theory_id: 8312
    - title: Intro to SQL Alchemy
      theory_id: 12935
    - title: Intro to MySQL
      theory_id: 16662
    - title: SQL Alchemy mappings
      theory_id: 13033
    - title: Basic UPDATE statement
      theory_id: 9067
    - title: Updating selected rows
      theory_id: 9603
    - title: SQL Alchemy updating and deleting data
      theory_id: 15776
    - title: Alter table
      theory_id: 9579
    - title: PRIMARY KEY constraint
      theory_id: 9781
  3:
    - title: For loop
      theory_id: 6065
    - title: SQL Alchemy querying and filtering
      theory_id: 15111
    - title: Tuple
      theory_id: 7462
